### ISSUE TITLE
Can't install on Firefox 102

### ISSUE THREAD

**Issue by cxumol** [OverflowCat/simpread-firefox#1]
On Firefox 102

Download https://github.com/OverflowCat/simpread-firefox/releases/download/publish/simpread.zip

![image](https://user-images.githubusercontent.com/8279655/177901756-c828ac15-99ac-4ad0-bc25-76af0ff75dfe.png)

And then, 
![image](https://user-images.githubusercontent.com/8279655/177901514-aaba815a-069e-487b-b596-8913209cb53f.png)

**Comment by OverflowCat** [comment]
@cxumol This problem is caused by manifest warnings of unexpected properties, which may be introduced by new versions of FireFox. Tested on Developer Edition v103.0b6(64bit), Windows 11, [this](https://github.com/OverflowCat/simpread-firefox/releases/download/publish-2/simpread-firefox.zip) should fix. Still, SimpRead Premium won't work on this ported version. I recommend you use any of the Chromium browsers if you need that.

**Comment by cxumol** [comment]
@OverflowCat Thank you for your fix. I'm a firm Firefox user and I won't pay for SimpRead Premium. I believe both Greasyfork and addons.mozilla.org have their own reasons to remove SimpRead.
